### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#1]
I added the installation instructions to the README. When I follow them, I get:

```
traceback (most recent call last):
  File "zpapi", line 3, in <module>
    from dotenv import load_dotenv, find_dotenv
ModuleNotFoundError: No module named 'dotenv'
bjohas@bjoga:~/Downloads/pyzotero-cli-argparse$ 
```

**Comment by retorquere** [comment]
You need to run `pip3 install -r requirements.txt` first. Whenever you see a `requirements.txt` in a python project you want to run that command.

**Comment by retorquere** [comment]
Wait, you've run this and you're still getting this error?

**Comment by retorquere** [comment]
How are you running the script?

**Comment by retorquere** [comment]
And what does `pip3 list | grep dotenv` show?

**Comment by bjohas** [comment]
Sorry, it's working now. I re-ran requirements.txt. I must have somehow missed something before. It works now - thanks.
