### ISSUE TITLE
Reflect the any error responses from the API in the exit status of zotero-cli

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#105]
If I run zotero-cli from another script, how do I know whether the API query completed successfully? Adjust the exit status of zotero-cli depending on whether API query was successful or not.

**Comment by a1diablo** [comment]
I'm not able to get the response codes from the Zotero API to detect the success/failure of the API call.

I tried `resolveWithFullResponse: true` option in the request but did not get statusCode in the response. I also tried the **item add to collection** API request on a rest client (Insomnia), but no content was received in response. I'm not sure what am I missing here.  @retorquere did this ever work for you?

**Comment by retorquere** [comment]
I haven't tested for failures, but I'd expect the API to use standard HTTP response codes. `resolveWithFullResponse: true` just means that in addition to the response code, you'll also get the body text that was sent -- the body text might be informative for finding out the reason for the failure, but there are no guarantees that the body text will be useful at all, and it should not be relied upon.

request-promise just throws an error when a request fails, and that's catchable:

```
const request = require('request-promise')

async function go() {
  try {
    return await request({
      method: 'POST',
      uri: 'https://api.zotero.org/users/475425/collections/9KH9TNSJ/items/top?v=3',
      body: { some: 'payload' },
      json: true,
    })
 
  } catch (err) {
    console.log('oops:', err.statusCode)
    return null
  }
}

go()
```

**Comment by a1diablo** [comment]
Thanks for the info. That means that if we handle all API exceptions, we can use it to return the correct exit code from the script. @bjohas would that suffice?

**Comment by retorquere** [comment]
You can probably just let the exceptions bubble up to the top level and generically handle them there.

**Comment by a1diablo** [comment]
@retorquere Makes more sense, thanks!
