### ISSUE TITLE
Zotero.children(itemID[, search/request parameters])

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#19]
Returns the child items of a specific item

**Comment by bjohas** [comment]
I cannot call this?

**Comment by bjohas** [comment]
zotero-cli.ts: error: argument "command": Invalid choice: children (choose from [key, collection, collections, items, item, publications, trash, tags, searches, attachment, types, fields])

**Comment by retorquere** [comment]
It's items --children

**Comment by bjohas** [comment]
Yes thanks - my bad!
