### ISSUE TITLE
Zotero.last_modified_version()

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#46]
If you wish to retrieve the last modified version of a library, you
can use the following method: Returns the last modified version of
the library

**Comment by bjohas** [comment]
This seems kinda important, so that we know we are operating on the last version?

**Comment by retorquere** [comment]
We're automatically operating on the last modified version. last-modified-version is only relevant for sync.

**Comment by bjohas** [comment]
E.g. patch and put need this - but I assume it'll be handled as part of those calls.

**Comment by retorquere** [comment]
If you get the item, they'll already have the `version`, why add a separate method?

**Comment by bjohas** [comment]
Yes, agreed.
