### ISSUE TITLE
Zotero.saved_search(name, conditions)

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#48]
Create a new saved search. conditions is a list of one or more dicts,
each of which must contain the following three string keys: condition,
operator, value. See the documentation for an example.

```
def zotero_saved_search(zot, **filter):
    if filter:
        print("--filter has no effect for this action.")
    if args.files is None:
        print("No positional arguments.")
        exit()
    for file in arg.files:
        print("Search file: " + file)
        with open(file) as json_file:  
            searchdefs = json.load(json_file)
            for mydef in searchdefs:
                print("   Adding: "+ mydef['name']);
                result = zot.saved_search(mydef['name'], mydef['conditions'])
                print(json.dumps(result))
    print("Done")
```

**Comment by a1diablo** [comment]
Similar query regarding the command format for the same.
Endpoint details for reference:
![image](https://user-images.githubusercontent.com/8023502/82831965-c0d7f580-9eb1-11ea-8bcb-d5b571a7c703.png)

**Comment by bjohas** [comment]
How about
```
zotero-cli createsearch search.json
```
?

**Comment by bjohas** [comment]
Or better
```
zotero-cli createsearchES search.json
```
-> The format should always be as above (i.e., an array) but the tool should allow creating several searches in one file. 

Basically, it should be possible for do this
```
get searches from library A -> save to searches.json
```
followed by
```
save searches.json to library B
```

**Comment by a1diablo** [comment]
@bjohas Should it look like 
```
zotero-cli searches --create search.json
```
?
