### ISSUE TITLE
Implement a tag-counter

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#5]
I had originally written this code:
```
# Note - this doesn't seem to work!
# https://github.com/urschrei/pyzotero/issues/93
def count_items_with_tag(zot, **filter):    
    if filter:
        items = zot.everything(zot.tags(filter))
    else:
        items = zot.everything(zot.tags())
    # print(json.dumps(items, indent=jsonIndent))
    for tag in items:
        items = zot.num_tagitems(tag)
        print(tag + " " + items)
```
However, it turns out that this doesn't work, as the API doesn't (currently?) support this.

Could you implement a tag counter as above?

**Comment by retorquere** [comment]
That's very expensive to do with pyzotero. I'll see if I can work with stephan to make it feasible.

**Comment by bjohas** [comment]
A related issue on pyzotero was resolved earlier: https://github.com/urschrei/pyzotero/issues/93. I wonder whether this changes anything.

**Comment by retorquere** [comment]
No, that's different. That would fail everywhere. This one fails for a part of the zotero api, only on macos Mojave.
