### ISSUE TITLE
Zotero.show_conditions()

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#51]
Show available saved search conditions

**Comment by a1diablo** [comment]
I think this is already implemented?

**Comment by bjohas** [comment]
We do have the listing of searches, but we dn't have the listing of permitted operators. This should be a static list, independent of collection (if I remember rightly).

**Comment by a1diablo** [comment]
I'm not sure how to retrieve this list. The API doc only seems to have this endpoint:
![image](https://user-images.githubusercontent.com/8023502/82751775-8424d500-9db1-11ea-86d3-da12f7d2b49d.png)

There is a similar issue: [https://github.com/edtechhub/zotero-cli/issues/50](url)

**Comment by bjohas** [comment]
Could you see how it's implemented here?
```
.. py:method:: Zotero.show_conditions()

    Show available saved search conditions

    :rtype: list

.. py:method:: Zotero.show_condition_operators(condition)

    Show available operators for a given saved search condition

    :param str condition: a valid saved search condition
    :rtype: list
```
It's possible that it's not an actual API call (or reference to some file provided by Zotero), but just coded into the library. In that case, don't worry! However, it if fetches some information, then do get it from Zotero. Same with https://github.com/edtechhub/zotero-cli/issues/50

**Comment by a1diablo** [comment]
Need more clarification. This is a sample output from searches:

```
[
   {
      "key": "V6BX37AF",
      "version": 406,
      "library": {
         "type": "user",
         "id": 6525976,
         "name": "aldiablo",
         "links": {
            "alternate": {
               "href": "https://www.zotero.org/aldiablo",
               "type": "text/html"
            }
         }
      },
      "links": {
         "self": {
            "href": "https://api.zotero.org/users/6525976/searches/V6BX37AF",
            "type": "application/json"
         }
      },
      "data": {
         "key": "V6BX37AF",
         "version": 406,
         "name": "test 1",
         "conditions": [
            {
               "condition": "title",
               "operator": "contains",
               "value": "dgfgdf"
            }
         ]
      }
   }
]
```

What would be the expected output for conditions and operators for this?

conditions => ['title']
operators => ['contains']

Is the above understanding correct? Also, there is no implementation for the functions you pointed out in the pyzotero code.

**Comment by retorquere** [comment]
I'm not sure whether this is retrievable by API. https://www.zotero.org/support/dev/web_api/v3/basics lists the possible search terms I think.

**Comment by bjohas** [comment]
Seems that this is not possible via API.
