### ISSUE TITLE
Zotero.upload\_attachments(attachments[, parentid, basedir=None])

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#65]
Upload files to their corresponding attachments. If the attachments
lack the key property they are assumed not to exist and will be
created. The parentid parameter is not compatible with existing
attachments. In order for uploads to succeed, the filename parameter
of each attachment must resolve.  (Attachment methods are in beta.)

**Comment by bjohas** [comment]
This isn't relevant
