### ISSUE TITLE
Zotero.create\_collections(dicts[, last\_modified])

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#69]
Create a new collection in the Zotero library

**Comment by a1diablo** [comment]
This is not implemented in the pyzotero. However, there is an API to do that. What is the expected command format for the same?

Here are the endpoint details for reference:
![image](https://user-images.githubusercontent.com/8023502/82831717-19f35980-9eb1-11ea-8370-9bee6e05b6ac.png)

**Comment by bjohas** [comment]
Maybe
```
zotero-cli createcollection --parent KEY --title "new collection"
```
?

**Comment by bjohas** [comment]
Actually, maybe this should be part of the 
```
zotero-cli collection --key --child "new collection"
```
?

The only question is whether that allows creating collections at the top level. I would make this dependent on the API. If it's a different endpoint in the API, use the API endpoint to make it. If it's the same endpoint, then use the same verb. (Same for the saved searches.)

**Comment by retorquere** [comment]
Omission of the parent should create a toplevel collection.

**Comment by a1diablo** [comment]
@bjohas So far we have separate verbs for `create` and `update` for `item` even though the endpoint is the same. Do we want to change the pattern starting now? Also, `searches` is the same endpoint for getting/creating but we have different verbs `searches` (get) and `create-searches` (create) as of now.

**Comment by bjohas** [comment]
I think the same endpoint should have the same verb, unless it's a very complex end point.

Use the same verb for the search get/create. 

Let me think about the create and update one - maybe there was a logic to it.
