### ISSUE TITLE
Suggestion for implementation are available in 'pyzotero-cli/list-of-api-calls.py' 

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#7]
I've made a shortlist of things we could look at in the first instance, see  'pyzotero-cli/list-of-api-calls.py' 

For the items that only require commands, but no further arguments (such as itemIDs, collectionID, etc) I could easily replicate from what you have already. However, there may be surprises when we try to use them, so it may be better for your to implement and do a basic test. I can then do furtehr testing.

For commands that require further arguments  (such as itemIDs, collectionID, etc) it would be good to see how you recommend that this be done. I can then replicate that code again.

**Comment by retorquere** [comment]
At this stage I think it's more important to think about what you want the command line structure to look like than implementing the backend. If you can make a list of that, I can start figuring out how to implement them.
