### ISSUE TITLE
Zotero.addto_collection(collection, item)

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#71]
Add the specified item(s) to the specified collection

**Comment by bjohas** [comment]
We would like to be able to add a set of items to a specific collection, e.g.

 zotero-cli addtocollection --collection ABC item1 [item2 [item3 ...]]

which would add items1 (2, 3, ...) to collection ABC.

**Comment by retorquere** [comment]
with items being? Individual JSON documents such as fetched with `items --top`? Arrays of such (which is what the `items` call would usually return)?

Would this create the items, or merely assign existing items to existing collections? 

How should nested collections be specified (keeping in mind that Zotero allows same-name collections on the same level)?

**Comment by bjohas** [comment]
The Zotero collection should be describe as the ID of the collection (e.g. fetched with the additions you did for Zutilo).

Items should be specified as item IDs, i.e. libraryID:ittemID.

See also https://github.com/edtechhub/zotero-cli/issues/90

**Comment by retorquere** [comment]
The API doesn't know about itemIDs, it only knows itemKeys, and you don't need to specify a libraryID because items can only be added to collections that are part of the same library.

Specifying via key means I must download the item and patch it, so there's a round-trip involved, and it can fail if someone has changed the item between the fetch and the patch.

**Comment by retorquere** [comment]
Is there a collection and items I can test with safely?

**Comment by retorquere** [comment]
You can try 1.0.2

**Comment by bjohas** [comment]
Thank you!

All working. I made a small tweak (as well as some redundant changes that I then undid).

Many thanks!
