### ISSUE TITLE
How do I use "npm start -- items" ?

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#83]
Zotero.items([search/request parameters])    
Add documentation: Returns Zotero library items

Please provide examples how to use this function, providing a search/request param?

**Comment by retorquere** [comment]
It's no different than you would with pyzotero. It's a straight port of the --filter that was there - if you want something else, I'd really need you to spec out what you want instead of "as pyzotero does it"

**Comment by bjohas** [comment]
OK, great - I just didn't know how to find the 'subcommands' i.e. "items --help".
