### ISSUE TITLE
implement --get API_PATH

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#87]
I'd suggest implementing a 
```
zotero-cli --get API_PATH
```
e.g. the api method "GET /itemFields" becomes
```
zotero-cli --get /itemFields
```

Ratoinale: This would allow accessing api functions that I won't need to use often. However, when I do need to use them, I then don't don't need to worry about authentication.

**Comment by retorquere** [comment]
The top-level options are supposed to apply to most commands, this wouldn't really. I'd suggest `zotero-cli get /itemFields` instead.

**Comment by retorquere** [comment]
It'd be a big help if you could start adding doc strings to the command functions BTW.
