### ISSUE TITLE
js ./bin/zotero-cli.js collection --key COLLECTIONID --remove ITEMID

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#92]
Add a facility for removing an item from a collection (in analogy to add).

It would be good to do this with the collection verb:
```
js ./bin/zotero-cli.js collection --item COLLECTIONID --remove ITEMID
```

**Comment by bjohas** [comment]
Addressed by https://github.com/edtechhub/zotero-cli/pull/104

**Comment by bjohas** [comment]
@a1diablo - would you be able to add documentation, so it comes up under
```
zotero-cli collection --help
```
? Thanks!

**Comment by a1diablo** [comment]
![image](https://user-images.githubusercontent.com/8023502/82739189-877a7b00-9d35-11ea-8778-1c42ad3c221e.png)
I think it is there already?

**Comment by bjohas** [comment]
I don't have this. Could you push?

**Comment by bjohas** [comment]
Or is it a different branch?

**Comment by a1diablo** [comment]
It's already merged into the master. How are you running the command?

**Comment by bjohas** [comment]
```
$ zotero-cli collection --help
usage: zotero-cli collection [-h] --key KEY [--tags] [--add]
                             [itemkeys [itemkeys ...]]

Retrieve information about a specific collection --key KEY (API: 
/collection/KEY or /collection/KEY/tags)

Positional arguments:
  itemkeys

Optional arguments:
  -h, --help  Show this help message and exit.
  --key KEY   The key of the item.
  --tags      Display tags present in the collection.
  --add       Add items to this collection.
```

**Comment by bjohas** [comment]
I've also checked that I am on the master branch.

**Comment by a1diablo** [comment]
Did you build using `npm run build` before running?

**Comment by bjohas** [comment]
No, I did not.... :(

Thank you!!!
