### ISSUE TITLE
Item-based adding to collection

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#93]
I am not sure whether this is easy to implement, but if yes, then it's worth having.

As the collection process is item-based, it woudl make sense to be able to change/remove multiple collections in one go:
```
 js ./bin/zotero-cli.js item --key ABC --addtocollection=DEF --removefromcollection=GHI,JKL
```

**Comment by a1diablo** [comment]
I believe this is already done?

**Comment by bjohas** [comment]
No. Run:
```
zotero-cli item --help
```
vs.
```
zotero-cli collection --help
```
The idea is to have this item based, so that you have the choice whether to do multiple collection operations on one item, or do multiple item operations on one collection.

**Comment by a1diablo** [comment]
#106
