### ISSUE TITLE
Introductions @a1diablo and @retorquere

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#97]
Hello @a1diablo and @retorquere,

@retorquere: @a1diablo is also going to contribute to this script., via PRs. He'll use existing coding conventions. Just so that you know!

Issue can be closed!

Thanks!
Björn

**Comment by retorquere** [comment]
That's fine, but how should I interpret this being assigned to me then?

**Comment by retorquere** [comment]
Make sure to run `npm test` before committing.
