### ISSUE TITLE
Implement --out option

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-cli#98]
It would be good to have an `--out file.json` option that redirects outputs to a file called file.json.

**Comment by bjohas** [comment]
I cannot find a branch relating to this.

**Comment by retorquere** [comment]
I always name branches after the issue name -- this change is on branch `gh-89` : https://github.com/edtechhub/zotero-cli/blob/gh-89/bin/zotero-cli.ts#L64

**Comment by retorquere** [comment]
Have you pulled before trying to switch to the branch?

**Comment by retorquere** [comment]
A quick way to test the current state without going through a build step (although that should just work) is to run `npm start -- <any other parameters you would otherwise use>`. Just running `npm start` will show the usage, which on `gh-89` looks like this:

```
usage: zotero-cli.ts [-h] [--api-key API_KEY] [--config CONFIG]
                     [--user-id USER_ID] [--group-id GROUP_ID]
                     [--indent INDENT] [--out OUT] [--verbose]
                     
                     {attachment,collection,collections,create-item,fields,get,item,items,key,publications,searches,tags,trash,types,update-item}
                     ...
zotero-cli.ts: error: too few arguments
```

**Comment by retorquere** [comment]
Is there a lib I can safely test against?

**Comment by bjohas** [comment]
Safely test the --out?  That should be non-descructive, right?

Or do you mean for the other scripts?

**Comment by retorquere** [comment]
No just safely test anything.

**Comment by bjohas** [comment]
I have an API testing library - let me add you.

gh-89 - great. I looked for gh-98 :)

**Comment by bjohas** [comment]
This issue can be closed.
